const priceData = {
  Therapy: [
    { key: "scaling", price: "100₾" },
    { key: "complexCleaning", price: "200₾" },
    { key: "cleaningAirflow", price: "100₾" },
    { key: "deepCleaningPerio", price: "100₾" },
    { key: "gumTreatmentVector", price: "600₾" },
    { key: "visiography", price: "6₾" },
    { key: "rootCanal", price: "100₾" },
    { key: "periodontitis", price: "250₾" },
    { key: "healingMedOneCanal", price: "15₾" },
    { key: "marylandBridge", price: "350₾" },
    { key: "cavityImprint", price: "50₾" },
    { key: "raberdamSystem", price: "15₾" },
    { key: "retractor", price: "15₾" },
    { key: "caries", price: "150₾+" },
    { key: "restorationVeneer", price: "200₾" },
    { key: "restorationMocaf", price: "200₾" },
    { key: "siliconeKey", price: "85₾" },
    { key: "cultUnderCrown", price: "60₾" },
    { key: "endoWhitening", price: "60₾" },
    { key: "whiteningCaps", price: "550₾" },
  ],

  Implantology: [
    { key: "implRoot", price: "1200₾" },
    { key: "implMisSeven", price: "1200₾" },
    { key: "implStraumann", price: "2200₾" },
    { key: "implMisCi", price: "1200₾" },
    { key: "implSwedenMartina", price: "1500₾" },
    { key: "gumCorrection", price: "200-800₾" },
    { key: "sinusLiftOpen", price: "2200₾" },
    { key: "sinusLiftClosed", price: "1700₾" },
    { key: "boneAugmentation", price: "1000₾+" },
    { key: "softTissueAugmentation", price: "150-600₾" },
    { key: "tempAbutment", price: "250₾" },
    { key: "gumShaper", price: "120₾" },
    { key: "surgicalTemplatePart", price: "350₾" },
    { key: "surgicalTemplateJaw", price: "350₾" },
  ],

  Orthopedics: [
    { key: "ceramicVeneer", price: "600₾" },
    { key: "zirconCrown", price: "550₾" },
    { key: "metalCrown", price: "250₾" },
    { key: "metalCrownImplant", price: "450₾" },
    { key: "zirconImplant", price: "650₾" },
    { key: "microProsthesis", price: "150₾" },
    { key: "removableProsthesis", price: "600-800₾" },
    { key: "bugleProsthesis", price: "1500-2500₾" },
    { key: "valplastProsthesis", price: "1500₾" },
    { key: "tempToothOne", price: "80₾" },
    { key: "tempToothMany", price: "50₾" },
    { key: "metalInlay", price: "150₾" },
    { key: "zirconInlay", price: "200₾" },
    { key: "arcProsthesisLock", price: "6000₾" },
    { key: "arcProsthesisAttach", price: "4500₾" },
  ],

  Orthodontics: [
    { key: "damonQ", price: "3800₾" },
    { key: "damonClear", price: "4200₾" },
    { key: "americanOrtho", price: "2000₾" },
    { key: "ormco", price: "1800₾" },
    { key: "inspireIce", price: "2200₾" },
    { key: "correctionStandard", price: "70₾" },
    { key: "correctionDamon", price: "100₾" },
    { key: "attachBracket", price: "50₾" },
    { key: "attachLostStd", price: "100₾" },
    { key: "attachLostDamon", price: "100₾" },
    { key: "retainerOneJaw", price: "150₾" },
    { key: "retainerCap", price: "200₾" },
    { key: "miniImplant", price: "450₾" },
    { key: "myobrace", price: "450₾" },
  ],

  Surgery: [
    { key: "regionalAnesthesia", price: "20₾" },
    { key: "infiltrativeAnesthesia", price: "15₾" },
    { key: "extraction", price: "80₾" },
    { key: "complexExtraction", price: "100-120₾" },
    { key: "rootExtraction", price: "50₾" },
    { key: "tooth8Extraction", price: "120₾" },
    { key: "tooth8Retention", price: "250-350₾" },
    { key: "exostosisSection", price: "50₾" },
    { key: "abscessRemoval", price: "60₾" },
    { key: "curettage", price: "40₾" },
    { key: "suturing", price: "20₾" },
  ],

  Pediatrics: [
    { key: "cleaning", price: "150₾" },
    { key: "cariesChild", price: "70₾" },
    { key: "pulpit", price: "80₾" },
    { key: "periodontitisChild", price: "90₾" },
    { key: "fissureSeal", price: "70₾" },
    { key: "milkExtraction", price: "40₾" },
    { key: "frenulumCorrection", price: "200₾" },
  ],
};

export default priceData;
